CREATE TABLE IF NOT EXISTS system_storage_quotas (
    id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    max_bytes BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

INSERT INTO system_storage_quotas (id, max_bytes)
VALUES (1, 10737418240)
ON DUPLICATE KEY UPDATE id = id;
